import type { CalcModel } from "@/calc/model"

const pocChf = [
  10_000, 18_000, 24_000, 24_000, 79_000, 44_000, 10_000, 6_000,
] as const
const mvpChf = [190_800, 118_000, 242_000, 234_000] as const

/** Values transcribed from `Digital_Assistant_Szenario_Berechnung_v11-1.xlsx`. */
export const defaultModel: CalcModel = {
  horizonYears: 5,
  usage: {
    potentialUsers: 654,
    activeUserShareY: [0.35, 0.6, 0.75, 0.9, 0.9],
    interactionsPerActiveUserPerWorkday: 4,
    workdaysPerYear: 312,
    workdaysPerMonth: 21,
    operatingHoursPerDay: 10,
    inputTokensPerInteraction: 2400,
    outputTokensPerInteraction: 500,
    imageInteractionFraction: 0.15,
    extraInputTokensForImage: 1200,
    ragInteractionFraction: 0.6,
    actionInteractionFraction: 0.25,
    actionsPerInteraction: 4,
    peakLoadMultiplier: 2.2,
  },
  fteCosts: {
    monthlyBusinessCHF: 14_000,
    monthlyPlatformCHF: 18_000,
    monthlyContentCHF: 13_000,
  },
  benefits: {
    unnecessarySaReductionFraction: 0.2,
    returnedServiceOrdersPerYear: 50_690,
    minutesPerUnnecessarySa: 23,
    fullCostServiceTechCHFPerHour: 55,
    minutesSavedPerReturnedSa: 2,
    serviceCenterCHFPerHour: 60,
    directCreditsPerYear: 100_827,
    directCreditVolumeCHF: 2_771_783,
    directCreditReductionFraction: 0.2,
    overrideAvoidedUnnecessarySa: 13_400,
    overrideAvoidedWrittenRequests: 40_620,
    minutesPerWrittenRequest: 10,
    overrideRemainingOptimizedRequests: 162_480,
    remainingRequestTimeSavingFraction: 0.333,
    overrideAvoidedDirectCredits: 20_475,
    overrideDirectCreditBenefitCHF: 697_289,
    conservativeEfficiencyFactor: 0.75,
  },
  commercial: {
    activeInBaseCase: false,
    haircutFraction: 0.5,
    conversionUpliftCurrentCHFGross: 475_100.354_400_000_77,
  },
  phase: {
    pocExternalPdBase: 107.5,
    pocInternalPdBase: 41,
    mvpExternalPdBase: 357.4,
    mvpInternalPdBase: 130,
    pocPhaseExtChfBaseline: [...pocChf],
    mvpBlockExtChfBaseline: [...mvpChf],
  },
  scenarios: [
    {
      id: "copilot",
      name: "Copilot Studio",
      costFactor: 0.85,
      pricingMode: "credits",
      creditsPerInteraction: 10,
      chfPerCredit: 0.0088,
      tokenInputChfPerM: 0,
      tokenOutputChfPerM: 0,
      realizationEfficiency: 0.85,
      realizationCommercial: 0.45,
      operating: {
        ftePO: 0.3,
        fteContentOps: 0.35,
        ftePlatform: 0.4,
        fteQA: 0.2,
        externalSupportMonthlyCHF: 2000,
        hypercareContentFteY1: 0.2,
      },
      platformInfraMonthlyCHF: [0, 0, 0, 0, 0, 0, 0, 0, 0, 200, 550],
    },
    {
      id: "azure",
      name: "Azure Komponenten",
      costFactor: 1.15,
      pricingMode: "tokens",
      creditsPerInteraction: 10,
      chfPerCredit: 0.0088,
      tokenInputChfPerM: 2.5,
      tokenOutputChfPerM: 15,
      realizationEfficiency: 0.95,
      realizationCommercial: 0.85,
      operating: {
        ftePO: 0.35,
        fteContentOps: 0.35,
        ftePlatform: 0.5,
        fteQA: 0.25,
        externalSupportMonthlyCHF: 2500,
        hypercareContentFteY1: 0.2,
      },
      platformInfraMonthlyCHF: [
        1100, 2300, 0, 180, 30, 130, 16, 5, 0, 0, 0,
      ],
    },
    {
      id: "oss-azure",
      name: "Open Source auf Azure",
      costFactor: 1.2,
      pricingMode: "tokens",
      creditsPerInteraction: 10,
      chfPerCredit: 0.0088,
      tokenInputChfPerM: 0.5,
      tokenOutputChfPerM: 3,
      realizationEfficiency: 0.95,
      realizationCommercial: 0.9,
      operating: {
        ftePO: 0.4,
        fteContentOps: 0.4,
        ftePlatform: 0.6,
        fteQA: 0.3,
        externalSupportMonthlyCHF: 1500,
        hypercareContentFteY1: 0.25,
      },
      platformInfraMonthlyCHF: [
        245, 450, 0, 90, 30, 70, 16, 5, 0, 160, 0,
      ],
    },
    {
      id: "gcp-vertex",
      name: "GCP Vertex AI",
      costFactor: 1.0,
      pricingMode: "tokens",
      creditsPerInteraction: 10,
      chfPerCredit: 0.0088,
      tokenInputChfPerM: 1,
      tokenOutputChfPerM: 6,
      realizationEfficiency: 0.9,
      realizationCommercial: 0.7,
      operating: {
        ftePO: 0.3,
        fteContentOps: 0.35,
        ftePlatform: 0.4,
        fteQA: 0.2,
        externalSupportMonthlyCHF: 1500,
        hypercareContentFteY1: 0.2,
      },
      platformInfraMonthlyCHF: [
        1250, 1500, 120, 0, 0, 20, 15, 0, 10, 0, 0,
      ],
    },
    {
      id: "gcp-custom",
      name: "GCP Komponenten",
      costFactor: 1.1,
      pricingMode: "tokens",
      creditsPerInteraction: 10,
      chfPerCredit: 0.0088,
      tokenInputChfPerM: 2,
      tokenOutputChfPerM: 12,
      realizationEfficiency: 0.95,
      realizationCommercial: 0.85,
      operating: {
        ftePO: 0.35,
        fteContentOps: 0.35,
        ftePlatform: 0.5,
        fteQA: 0.25,
        externalSupportMonthlyCHF: 1500,
        hypercareContentFteY1: 0.2,
      },
      platformInfraMonthlyCHF: [
        1250, 1500, 0, 40, 20, 20, 15, 0, 10, 0, 240,
      ],
    },
  ],
}

/** Deep clone for store reset / snapshots. */
export function cloneDefaultModel(): CalcModel {
  return structuredClone(defaultModel)
}
