import type { CalcModel, ScenarioModel, ScorecardEntry } from "@/calc/model"

const pocChf = [
  10_000, 18_000, 24_000, 24_000, 79_000, 44_000, 10_000, 6_000,
] as const
const mvpChf = [190_800, 118_000, 242_000, 234_000] as const

/**
 * Qualitative scorecard keys & German labels (sheet `03` rows 38–44).
 * Scoring 1–5, 5 = best outcome as indicated in the Excel comments.
 */
export const SCORECARD_DEFAULTS: ScorecardEntry[] = [
  { id: "ttv", labelDe: "Schnelle Umsetzung bis Marktreife (1–5)", score: 3 },
  { id: "flex", labelDe: "Flexibilität / Optimierbarkeit (1–5)", score: 3 },
  { id: "integration", labelDe: "Integrationsfähigkeit (1–5)", score: 3 },
  { id: "governance", labelDe: "Governance / Controls (1–5)", score: 3 },
  { id: "lockin", labelDe: "Vendor Lock-in Risiko (1–5)", score: 3 },
  { id: "future", labelDe: "Future-Readiness / modulare Architektur (1–5)", score: 3 },
  { id: "mcp", labelDe: "MCP-Readiness / Offenheit (1–5)", score: 3 },
]

function scorecard(values: number[]): ScorecardEntry[] {
  return SCORECARD_DEFAULTS.map((entry, i) => ({
    ...entry,
    score: values[i] ?? entry.score,
  }))
}

const scenarioSeed: ScenarioModel[] = [
  {
    id: "copilot",
    name: "Copilot Studio",
    narrative:
      "Low-Code-Plattform; 100% generative Antworten; MS verwaltet LLM (GPT-4o); Custom Connectors für MAM/Agronet nötig; keine CH-LLM-Residenz; ideal wenn 600 Nutzer bereits M365 Copilot haben.",
    costFactor: 0.85,
    pricingMode: "credits",
    creditsPerInteraction: 10,
    chfPerCredit: 0.0088,
    tokenInputChfPerM: 0,
    tokenOutputChfPerM: 0,
    realizationEfficiency: 0.85,
    realizationCommercial: 0.45,
    operating: {
      ftePO: 0.3,
      fteContentOps: 0.35,
      ftePlatform: 0.4,
      fteQA: 0.2,
      externalSupportMonthlyCHF: 2000,
      hypercareContentFteY1: 0.2,
    },
    platformInfraMonthlyCHF: [0, 0, 0, 0, 0, 0, 0, 0, 0, 200, 550],
    platformContingencyFraction: 0.1,
    scorecard: scorecard([4, 2, 3, 5, 1, 2, 2]),
  },
  {
    id: "azure",
    name: "Azure Komponenten",
    narrative:
      "Modulare Azure-Zielarchitektur; GPT-5.1 in Switzerland North bestätigt; volle CH-Datenresidenz; maximale Kontrolle über Prompts, RAG und Integrationen; Function Calling für alle 6 Systeme.",
    costFactor: 1.15,
    pricingMode: "tokens",
    creditsPerInteraction: 10,
    chfPerCredit: 0.0088,
    tokenInputChfPerM: 2.5,
    tokenOutputChfPerM: 15,
    realizationEfficiency: 0.95,
    realizationCommercial: 0.85,
    operating: {
      ftePO: 0.35,
      fteContentOps: 0.35,
      ftePlatform: 0.5,
      fteQA: 0.25,
      externalSupportMonthlyCHF: 2500,
      hypercareContentFteY1: 0.2,
    },
    platformInfraMonthlyCHF: [1100, 2300, 0, 180, 30, 130, 16, 5, 0, 0, 0],
    platformContingencyFraction: 0.1,
    scorecard: scorecard([4, 5, 4, 4, 3, 5, 5]),
  },
  {
    id: "oss-azure",
    name: "Open Source auf Azure",
    narrative:
      "Maximale Souveränität; selbst bestimmte LLM-Modelle, welche über APIs genutzt werden.",
    costFactor: 1.2,
    pricingMode: "tokens",
    creditsPerInteraction: 10,
    chfPerCredit: 0.0088,
    tokenInputChfPerM: 0.5,
    tokenOutputChfPerM: 3,
    realizationEfficiency: 0.95,
    realizationCommercial: 0.9,
    operating: {
      ftePO: 0.4,
      fteContentOps: 0.4,
      ftePlatform: 0.6,
      fteQA: 0.3,
      externalSupportMonthlyCHF: 1500,
      hypercareContentFteY1: 0.25,
    },
    platformInfraMonthlyCHF: [245, 450, 0, 90, 30, 70, 16, 5, 0, 160, 0],
    platformContingencyFraction: 0.1,
    scorecard: scorecard([2, 5, 3, 3, 5, 5, 5]),
  },
  {
    id: "gcp-vertex",
    name: "GCP Vertex AI",
    narrative:
      "GCP Agent Builder + Dialogflow CX + Gemini 3.1 Pro/Flash; managed Plattform; günstige Token-Kosten; keine CH-Datenresidenz (nur EU); ideal wenn GCP strategische Plattform.",
    costFactor: 1.0,
    pricingMode: "tokens",
    creditsPerInteraction: 10,
    chfPerCredit: 0.0088,
    tokenInputChfPerM: 1,
    tokenOutputChfPerM: 6,
    realizationEfficiency: 0.9,
    realizationCommercial: 0.7,
    operating: {
      ftePO: 0.3,
      fteContentOps: 0.35,
      ftePlatform: 0.4,
      fteQA: 0.2,
      externalSupportMonthlyCHF: 1500,
      hypercareContentFteY1: 0.2,
    },
    platformInfraMonthlyCHF: [1250, 1500, 120, 0, 0, 20, 15, 0, 10, 0, 0],
    platformContingencyFraction: 0.1,
    scorecard: scorecard([4, 5, 4, 3, 2, 4, 5]),
  },
  {
    id: "gcp-custom",
    name: "GCP Komponenten",
    narrative:
      "GCP Custom Stack: Cloud Run + Google ADK + Gemini API direkt + Firestore Vector Search; kein Vertex AI Search Overhead; günstigstes all-in OPEX; keine CH-Datenresidenz (nur EU); GCP-Engineering-Expertise nötig.",
    costFactor: 1.1,
    pricingMode: "tokens",
    creditsPerInteraction: 10,
    chfPerCredit: 0.0088,
    tokenInputChfPerM: 2,
    tokenOutputChfPerM: 12,
    realizationEfficiency: 0.95,
    realizationCommercial: 0.85,
    operating: {
      ftePO: 0.35,
      fteContentOps: 0.35,
      ftePlatform: 0.5,
      fteQA: 0.25,
      externalSupportMonthlyCHF: 1500,
      hypercareContentFteY1: 0.2,
    },
    platformInfraMonthlyCHF: [1250, 1500, 0, 40, 20, 20, 15, 0, 10, 0, 240],
    platformContingencyFraction: 0.1,
    scorecard: scorecard([3, 5, 4, 3, 3, 5, 5]),
  },
]

/** Values transcribed from `Digital_Assistant_Szenario_Berechnung_v11-1.xlsx`. */
export const defaultModel: CalcModel = {
  horizonYears: 5,
  scaling: {
    numberOfPoS: 193,
    serviceMAPerPoS: 3,
    serviceCenterUsers: 50,
    centralExperts: 25,
    usdChfFx: 0.8,
  },
  rates: {
    knowledgeSources: 7,
    coreSystems: 6,
    useCasesPhase1: 4,
    languagesWave1: 2,
    securityMultiplier: 1.15,
    externalDayRateCHF: 2000,
    internalDayRateCHF: 0,
    bisonDayRateCHF: 1394,
    servicePersonnelCHFPerHour: 50,
    productiveHoursPerFteYear: 1800,
    contingencyFraction: 0.1,
    hybridOnPremFactor: 1.2,
  },
  documents: {
    pimExport: 25_385,
    productImages: 75_379,
    sparePartImages: 23_150,
    mamPdfs: 2000,
    pagesPerPdf: 10,
    charsPerPage: 1500,
    mbPerPage: 0.3,
    serviceOrderCharacters: 400_000_000,
  },
  usage: {
    potentialUsers: 654,
    activeUserShareY: [0.35, 0.6, 0.75, 0.9, 0.9],
    interactionsPerActiveUserPerWorkday: 4,
    workdaysPerYear: 312,
    workdaysPerMonth: 21,
    operatingHoursPerDay: 10,
    inputTokensPerInteraction: 2400,
    outputTokensPerInteraction: 500,
    imageInteractionFraction: 0.15,
    extraInputTokensForImage: 1200,
    ragInteractionFraction: 0.6,
    actionInteractionFraction: 0.25,
    actionsPerInteraction: 4,
    peakLoadMultiplier: 2.2,
  },
  fteCosts: {
    monthlyBusinessCHF: 14_000,
    monthlyPlatformCHF: 18_000,
    monthlyContentCHF: 13_000,
  },
  benefits: {
    unnecessarySaReductionFraction: 0.2,
    returnedServiceOrdersPerYear: 50_690,
    minutesPerUnnecessarySa: 23,
    fullCostServiceTechCHFPerHour: 55,
    minutesSavedPerReturnedSa: 2,
    serviceCenterCHFPerHour: 60,
    directCreditsPerYear: 100_827,
    directCreditVolumeCHF: 2_771_783,
    directCreditReductionFraction: 0.2,
    overrideAvoidedUnnecessarySa: 13_400,
    overrideAvoidedWrittenRequests: 40_620,
    minutesPerWrittenRequest: 10,
    overrideRemainingOptimizedRequests: 162_480,
    remainingRequestTimeSavingFraction: 0.333,
    overrideAvoidedDirectCredits: 20_475,
    overrideDirectCreditBenefitCHF: 697_289,
    conservativeEfficiencyFactor: 0.75,
  },
  commercial: {
    activeInBaseCase: false,
    haircutFraction: 0.5,
    basketCurrentCHF: 103,
    basketBudgetCHF: 104.9,
    revenueOnlineCurrentCHF: 20_790_000,
    revenueOnlineBudgetCHF: 23_707_400,
    sessionsCurrentPerYear: 25_720_000,
    sessionsBudgetPerYear: 28_250_000,
    conversionRateCurrent: 0.0078,
    conversionRateBudget: 0.008,
    conversionRateNew: 0.0085,
    stationaryRevenueTotalCHF: 1_149_122_000,
    marginFraction: 0.2562,
    influencedStationaryShare: 0,
    basketUpliftFraction: 0,
    frequencyUpliftFraction: 0,
    sparePartsRevenueCHF: 2_106_028,
    sparePartsMarginFraction: 0.25,
    sparePartsUpliftFraction: 0,
    overrideGrossCHF: 0,
    useBudgetForOnline: false,
  },
  phase: {
    pocExternalPdBase: 107.5,
    pocInternalPdBase: 41,
    mvpExternalPdBase: 357.4,
    mvpInternalPdBase: 130,
    pocPhaseExtChfBaseline: [...pocChf],
    mvpBlockExtChfBaseline: [...mvpChf],
  },
  scenarios: scenarioSeed,
}

/** Deep clone for store reset / snapshots. */
export function cloneDefaultModel(): CalcModel {
  return structuredClone(defaultModel)
}
